# Generated by Django 3.1.3 on 2021-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_albums_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_songfile',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
